name: Notify on PR to main


on:
  workflow_run:
    workflows: ["Short Workflow"]
    types:
      - completed



jobs:
  notify:

    env:
        TELEGRAM_BOT: 7065918905:AAHa9mJCuCqA8DNh_-fYfwVcIZUdQqx2DR4
        TELEGRAM_CHAT_MR: -4245933292


    runs-on: ubuntu-latest

    steps:
      # - name: Extract branch name
      #   shell: bash
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      #   id: extract_branch


      - name: Send Telegram Notification
         
        run: |
          PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)


          curl -X POST -H "Content-Type: application/json" \
            -d "{
            \"chat_id\": \"$TELEGRAM_CHAT_MR\",
            \"text\": \"PR [${{ github.workflow.event.pull_request.title }}](${{ github.workflow.event.pull_request.html_url}})
            \n${{ github.workflow.event.pull_request.base.ref }} <-- steps.extract_branch.outputs.branch  ( ${{ github.workflow.event.repository.name }} )
            \nАвтор: ${{ github.workflow.event.pull_request.user.login }}
            \",
            \"parse_mode\": \"Markdown\"
            }" \
            https://api.telegram.org/bot$TELEGRAM_BOT/sendMessage
