name: Build Manuspect App

on:
  push:
    branches:
      - build
  pull_request:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4


    - name: HOME
      run: dir ${{ env.HOME }}
      # D:\a\flutter-brige\flutter-brige

    - name: \~
      run: dir ~\.
      # C:\Users\runneradmin


    # - name: Restore cached Rust and Flutter  dependencies
    #   id: cache-deps-restore
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target/
    #       ~/.flutter
    #       ${{ env.HOME }}/.pub-cache
    #     key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-deps-

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Flutter Rust Bridge Codegen
      run: cargo install flutter_rust_bridge_codegen

    - name: cargo
      run: dir ~\.cargo/

    - name: cargo/registry
      run: dir ~\.cargo/registry

    - name: c
      run: dir c:/

    - name: target
      run: dir ~\.


    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.22.3

    - name: flutter pub get
      working-directory: my_app
      run: flutter pub get

    
    - name: pub-cache
      run: dir ${{ env.HOME }}/.pub-cache



    - name: Bridge generate
      working-directory: my_app
      run: flutter_rust_bridge_codegen generate


    - name: Build the Flutter app
      run: flutter build windows --release
      working-directory: my_app


    - name: Save Rust and Flutter dependencies
      id: cache-deps-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target/
          ~/.flutter
          ${{ env.HOME }}/.pub-cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}