name: Build Manuspect App

on:
  push:
    branches:
      - build
  pull_request:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Restore cached Rust and Flutter dependencies
      id: cache-deps-restore
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ${{ env.HOME }}/.pub-cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Flutter Rust Bridge Codegen
      run: cargo install flutter_rust_bridge_codegen

    - name: Save Rust and Flutter dependencies
      id: cache-deps-save
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ${{ env.HOME }}/.pub-cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.22.3

    - name: Build the Flutter app
      run: flutter build windows --release
      working-directory: my_app