name: Build Manuspect App

on:
  push:
    branches:
      - build-2
  pull_request:
    branches:
      - build-2

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.22.3

    - name: flutter pub get
      working-directory: my_app
      run: flutter pub get

    - name: Create database.g.dart
      run: dart run build_runner build

    # - name: Restore cached Rust and Flutter  dependencies
    #   id: cache-deps-restore
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target/
    #       ~/.flutter
    #       ${{ env.HOME }}/.pub-cache
    #     key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-deps-

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Flutter Rust Bridge Codegen
      run: cargo install flutter_rust_bridge_codegen


    # - name: Set up Flutter
    #   uses: subosito/flutter-action@v2
    #   with:
    #     channel: stable
    #     flutter-version: 3.22.3

    # - name: flutter pub get
    #   working-directory: my_app
    #   run: flutter pub get

    # - name: Create database.g.dart
    #   run: dart run build_runner build

    - name: Bridge generate
      working-directory: my_app
      run: flutter_rust_bridge_codegen generate


    # - name: Build the Flutter app
    #   run: flutter build windows --release
    #   working-directory: my_app

    - name: Save Rust and Flutter dependencies
      id: cache-deps-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target/
          ~/.flutter
          ${{ env.HOME }}/.pub-cache
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/pubspec.yaml') }}