name: Short


on:
  pull_request:
    branches:
      - staging

env:
    TELEGRAM_BOT: 7065918905:AAHa9mJCuCqA8DNh_-fYfwVcIZUdQqx2DR4
    TELEGRAM_CHAT_MR: -4245933292
    MENTION: \@EvgeneKopylov  


jobs:
  short_job:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch


  notify:
    
    runs-on: ubuntu-latest

    needs: short_job

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch


      - name: Send Telegram Notification
        if: ${{ always() && needs.short_job.result == 'success' }}
        run: |
          PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)


          curl -X POST -H "Content-Type: application/json" \
          -d "{
          \"chat_id\": \"$TELEGRAM_CHAT_MR\",
          \"text\": \"Pull Request [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url}})
          
          ${{ github.event.pull_request.base.ref }} <-- ${{ steps.extract_branch.outputs.branch }}  ( ${{ github.event.repository.name }} )
          by ${{ github.event.pull_request.user.login }}
          
          Reviewer ${{ env.MENTION }}
          \",
          \"parse_mode\": \"Markdown\"
          }" \
          https://api.telegram.org/bot$TELEGRAM_BOT/sendMessage
